---
  - name: Make sure packages are installed
    become: true
    apt: name={{item}} state=installed
    with_items:
      - parted
      - xfsprogs

  - name: Check if mounted
    become: true
    raw: mount
    register: mnt_out
    ignore_errors: yes

#  - debug: var=mnt_out

  - name: Unmount device, if mounted
    become: true
    mount:
      name: "{{ mnt_loc }}"
      state: unmounted
    when: 'mnt_loc in mnt_out.stdout'

  - name: Test if the partition already exists
    shell: lsblk -o NAME | grep {{ partition_name }}
    become: true
    register: part_tst

  - name: Partition the new storage
    become: true
    raw: parted -s {{ dev_path }} mklabel gpt mkpart primary {{ storage.type }} 0% 100%
    when: not part_tst.stdout

  - name: Get TYPE
    become: true
    command: blkid -s TYPE -o value {{ partition_path }}
    register: type_out

  - set_fact:
      fs_type_curr: "{{ type_out.stdout }}"

#  - debug: var=fs_type_curr
#  - debug: var=storage.type

  - name: Make the "{{storage.type}}" File System
    become: true
    raw: mkfs.{{ storage.type }} {{ partition_path }} -f
    when: not fs_type_curr is defined or fs_type_curr == "" or fs_type_curr != storage.type

  - stat:
      path: "{{ mnt_loc }}"
    register: st

  - name: Kill {{ mnt_loc }} if it exists
    become: true
    file: path="{{ mnt_loc }}" state=absent

  - name: Mount up device to get uuid
    become: true
    mount:
      name: "{{ mnt_loc }}"
      src: "{{ partition_path }}"
      fstype: "{{ storage.type }}"
      opts: "rw,relatime,data=ordered"
      state: present

  - name: Get UUID
    command: blkid -s UUID -o value {{ partition_path }}
    register: uuid_out
    become: true

  - set_fact:
      uuid: "{{ uuid_out.stdout }}"

  - set_fact:
      mount_opts: "rw,relatime,data=ordered"
    when: storage.type == "ext4"

  - set_fact:
      mount_opts: "rw,relatime,attr2,inode64,noquota"
    when: storage.type == "xfs"

  - name: Unmount device
    become: true
    mount:
      name: "{{ mnt_loc }}"
      state: absent

  - name: Mount device and save to fstab
    become: true
    mount:
      name: "{{ mnt_loc }}"
      src: "UUID={{ uuid }}"
      fstype: "{{ storage.type }}"
      opts: "{{ mount_opts }}"
      state: mounted
